language: go
sudo: false
go:
  - 1.x
install: go get -u -t -v ./...
script: make -j releases
deploy:
  provider: releases
  api_key:
    secure: GBnAjbRNw6r6w9Xanx9F5dQBmzJdbST3BcWSFHqTH2C/fwTS4G4Zw+OiVz2t0Sx3My6dp1sJgdYHn6uqCJUcQfEgkO563vu0SNw63eaEwDYyosOgGGTC8W8b+S8EkL25kkTCFE5wLpnYMVDJR93uIyXE3JmPAEU4iZqCz7WFXDE+cLWqjIPipUh+eBLcgc0IS7I15QOBoP0i44umOVI2eqCNm3zqVU9AvF9tZxJZ/48KzTBUXxnM/8HTJJtyvMAx5xixsrtDJL192wOXh+bKB5M3YBFYold6FN66b/AuddB/L2jKGMS3VLdg4BP/Gk60WkKLd2mNF905ODG2XsqGdL31am+jv8L/l2EKkFjVOWCkQtmhLvz+3E8e9FaXETtd7DYWgp7/C/wKpBhPVwi1iTzfp7v0EGRIP4NC79xFN62HFlSwbr7EZ9K9PKkwSQJx/wc8cRsAqRJP49ieEAWrk9x0vylc8/hZVdxeDfT9i7fmahvS8MWinR6ut7pvZFvk48n02b84EXNmL8sEN4eX7+8tpP7ap1f/YDQaISZdpFopGhsiDBgm2UQO9xuvDJqu2hGDcO8ScNjzozcfBm0VBitG2Q+8rfYp3BBTZc6NkbGabbrxzLO5eGz1Wj68yA4oGJPmJMpnNi0ttLkcqkxtgIFlBdZjVP3KLoj8Y0K11Iw=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: riobard/go-shadowsocks2
    branch: master
    tags: true